# Generated by Django 3.1.7 on 2021-03-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=100)),
                ('pirce', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
